name: balena

on:
  pull_request_target:
    types: [opened, synchronize, closed, labeled]
    branches:
      - main

jobs:
  build:
    if: github.actor == github.repository_owner || contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: balena-io/balena-ci@v0.5.0
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ secrets.BALENA_FLEET_SLUG }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          versionbot: false
          environment: balena-cloud.com
          create_tag: true
